/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ProveedorDAO;
import Modelo.Proveedor;
import java.util.*;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Bian
 */
public class ventanaSeleccionarProveedor extends javax.swing.JFrame {

    ProveedorDAO provDAO = new ProveedorDAO();
    ventanaNuevoProd vNP = new ventanaNuevoProd();
    
    public ventanaSeleccionarProveedor() {
        initComponents();
        
        //tablaProveedor.getColumnModel().getColumn(4).setMaxWidth(0);
        //tablaProveedor.getColumnModel().getColumn(4).setMinWidth(0);
        //tablaProveedor.getColumnModel().getColumn(4).setPreferredWidth(0);
        
        llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProveedor = new javax.swing.JTable();
        btnAceptarSProv = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CUIT", "Nombre", "Dirección", "Teléfono", "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaProveedor.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jScrollPane1.setViewportView(tablaProveedor);
        if (tablaProveedor.getColumnModel().getColumnCount() > 0) {
            tablaProveedor.getColumnModel().getColumn(0).setResizable(false);
            tablaProveedor.getColumnModel().getColumn(1).setResizable(false);
            tablaProveedor.getColumnModel().getColumn(3).setResizable(false);
            tablaProveedor.getColumnModel().getColumn(4).setResizable(false);
            tablaProveedor.getColumnModel().getColumn(4).setPreferredWidth(0);
        }

        btnAceptarSProv.setText("Confirmar");
        btnAceptarSProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarSProvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(btnAceptarSProv)
                .addContainerGap(260, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAceptarSProv)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarSProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarSProvActionPerformed
        
        TableModel modelo = tablaProveedor.getModel();
        int [] indice = tablaProveedor.getSelectedRows();
        int id;
        List<Proveedor> listadoProveedor = new ArrayList();
        
        for(int i = 0; i < indice.length; i++)
        {
            id = Integer.parseInt(modelo.getValueAt(indice[i], 5).toString());
            listadoProveedor.add(provDAO.buscarPorId(id));
        }
        
        vNP.asignarProveedores(listadoProveedor);
        
        vNP.setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_btnAceptarSProvActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaSeleccionarProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaSeleccionarProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaSeleccionarProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaSeleccionarProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaSeleccionarProveedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarSProv;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaProveedor;
    // End of variables declaration//GEN-END:variables

    private void llenarTabla() {
        
        DefaultTableModel modelo = new DefaultTableModel();
        List<Proveedor> lista = provDAO.listar();
        String [] datos = new String[6];
                
        modelo.addColumn("CUIT");
        modelo.addColumn("Nombre");
        modelo.addColumn("Dirección");
        modelo.addColumn("Teléfono");
        modelo.addColumn("Estado");
        modelo.addColumn("ID");
        
        
        for(Proveedor p : lista)
        {
            datos[0] = String.valueOf(p.getCuit());
            datos[1] = p.getNombreCompleto();
            datos[2] = p.getDireccion();
            datos[3] = String.valueOf(p.getTelefono());
            if(p.isEstado())
            {
                datos[4] = "Habilitado";
            }
            else
            {
                datos[4] = "Deshabilitado";
            }
            datos[5] = String.valueOf(p.getId());
            modelo.addRow(datos);
        }
        tablaProveedor.setModel(modelo);
        tablaProveedor.getColumnModel().getColumn(5).setMaxWidth(0);
        tablaProveedor.getColumnModel().getColumn(5).setMinWidth(0);
        tablaProveedor.getColumnModel().getColumn(5).setPreferredWidth(0);
        tablaProveedor.getColumnModel().getColumn(5).setResizable(false);
        tablaProveedor.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION); 
          
    }
}
