package Modelo;
// Generated 10/07/2017 15:46:06 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Entrada generated by hbm2java
 */
public class Entrada  implements java.io.Serializable {


     private int id;
     private Producto producto;
     private Proveedor proveedor;
     private int cantidad;
     private Date fecha;
     private boolean estado;

    public Entrada() {
    }

    public Entrada(int id, Producto producto, Proveedor proveedor, int cantidad, Date fecha, boolean estado) {
       this.id = id;
       this.producto = producto;
       this.proveedor = proveedor;
       this.cantidad = cantidad;
       this.fecha = fecha;
       this.estado = estado;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }




}


