package Modelo;
// Generated 10/07/2017 15:46:06 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private int id;
     private Set proveedor = new HashSet(0);

    
     private String codigo;
     private String descripcion;
     private BigDecimal precio;
     private int stock;
     private int stockMinimo;
     private byte[] imagen;
     private boolean estado;
     //private Set entradas = new HashSet(0);
     //private Set salidas = new HashSet(0);

    public Producto() {
    }

	
    public Producto(int id/*, Proveedor proveedor*/, String codigo, String descripcion, BigDecimal precio, int stockMinimo, boolean estado) {
        this.id = id;
       // this.proveedor = proveedor;
        this.codigo = codigo;
        this.descripcion = descripcion;
        this.precio = precio;
        this.stock = 0;
        this.stockMinimo = stockMinimo;
        this.estado = estado;
    }
    public Producto(int id, Set proveedor, String codigo, String descripcion, BigDecimal precio, int stockMinimo, byte[] imagen, boolean estado/*, Set entradas, Set salidas*/) {
       this.id = id;
       this.proveedor = proveedor;
       this.codigo = codigo;
       this.descripcion = descripcion;
       this.precio = precio;
       this.stock = 0;
       this.stockMinimo = stockMinimo;
       this.imagen = imagen;
       this.estado = estado;
       //this.entradas = entradas;
       //this.salidas = salidas;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    public Set getProveedor() {
        return proveedor;
    }

    public void setProveedor(Set proveedor) {
        this.proveedor = proveedor;
    }
    /*public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }*/
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public int getStock() {
        return this.stock;
    }
    
    public void setStock(int stock) {
        this.stock = stock;
    }
    public int getStockMinimo() {
        return this.stockMinimo;
    }
    
    public void setStockMinimo(int stockMinimo) {
        this.stockMinimo = stockMinimo;
    }
    public byte[] getImagen() {
        return this.imagen;
    }
    
    public void setImagen(byte[] imagen) {
        this.imagen = imagen;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    /*public Set getEntradas() {
        return this.entradas;
    }
    
    public void setEntradas(Set entradas) {
        this.entradas = entradas;
    }
    public Set getSalidas() {
        return this.salidas;
    }
    
    public void setSalidas(Set salidas) {
        this.salidas = salidas;
    }*/




}


