package Modelo;
// Generated 10/07/2017 15:46:06 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor  implements java.io.Serializable {


     private int id;
     private String nombreCompleto;
     private long cuit;
     private String direccion;
     private boolean estado;
     private Integer telefono;
     //private Set entradas = new HashSet(0);
     //private Set productos = new HashSet(0);

    public Proveedor() {
    }

	
    public Proveedor(int id, String nombreCompleto, long cuit, boolean estado) {
        this.id = id;
        this.nombreCompleto = nombreCompleto;
        this.cuit = cuit;
        this.estado = estado;
    }
    public Proveedor(int id, String nombreCompleto, long cuit, String direccion, boolean estado, Integer telefono/*, Set entradas, Set productos*/) {
       this.id = id;
       this.nombreCompleto = nombreCompleto;
       this.cuit = cuit;
       this.direccion = direccion;
       this.estado = estado;
       this.telefono = telefono;
       //this.entradas = entradas;
       //this.productos = productos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombreCompleto() {
        return this.nombreCompleto;
    }
    
    public void setNombreCompleto(String nombreCompleto) {
        this.nombreCompleto = nombreCompleto;
    }
    public long getCuit() {
        return this.cuit;
    }
    
    public void setCuit(long cuit) {
        this.cuit = cuit;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }
   /* public Set getEntradas() {
        return this.entradas;
    }
    
    public void setEntradas(Set entradas) {
        this.entradas = entradas;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }*/




}


