package Modelo;
// Generated 10/07/2017 15:46:06 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Salida generated by hbm2java
 */
public class Salida  implements java.io.Serializable {


     private int id;
     private Cliente cliente;
     private Producto producto;
     private int cantidad;
     private Date fecha;
     private boolean estado;

    public Salida() {
    }

    public Salida(int id, Cliente cliente, Producto producto, int cantidad, Date fecha, boolean estado) {
       this.id = id;
       this.cliente = cliente;
       this.producto = producto;
       this.cantidad = cantidad;
       this.fecha = fecha;
       this.estado = estado;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
   
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }




}


